#!/usr/bin/env python3
"""
Create users table and insert default admin user
"""
import pg8000.dbapi

# Database connection parameters
DB_HOST = "192.168.1.160"
DB_PORT = 5432
DB_NAME = "crm"
DB_USER = "postgres"
DB_PASSWORD = "Afa123456@"

# BCrypt hash for password "Afa123456@"
# This is a placeholder - the actual BCrypt hash will be generated by the Java application
# For now, we'll insert a dummy password and let the user register properly
BCRYPT_PASSWORD = "$2a$10$dummyHashForNow"

def main():
    try:
        # Connect to database
        conn = pg8000.dbapi.connect(
            host=DB_HOST,
            port=DB_PORT,
            database=DB_NAME,
            user=DB_USER,
            password=DB_PASSWORD
        )
        print("✓ Connected to PostgreSQL database")
        
        cursor = conn.cursor()
        
        # Create users table
        create_table_sql = """
        CREATE TABLE IF NOT EXISTS users (
            id SERIAL PRIMARY KEY,
            username VARCHAR(50) UNIQUE NOT NULL,
            password VARCHAR(200) NOT NULL,
            real_name VARCHAR(100),
            role VARCHAR(20) DEFAULT 'user',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
        cursor.execute(create_table_sql)
        conn.commit()
        print("✓ Users table created successfully")
        
        # Check if admin user exists
        cursor.execute("SELECT COUNT(*) FROM users WHERE username = 'admin'")
        result = cursor.fetchone()
        count = result[0]
        
        if count == 0:
            # Insert admin user
            # Note: The password hash here is just a placeholder
            # User should change password or we need to generate proper BCrypt hash
            insert_sql = """
            INSERT INTO users (username, password, real_name, role)
            VALUES (%s, %s, %s, %s)
            """
            # We'll insert with a flag to force password change, or use a known BCrypt hash
            # For now, let's just create the user and note that password needs to be set
            cursor.execute(insert_sql, ['admin', BCRYPT_PASSWORD, 'Administrator', 'admin'])
            conn.commit()
            print("✓ Admin user created successfully")
            print("  Username: admin")
            print("  ⚠️  Password hash is a placeholder - need to update via application")
            print("  Run registration endpoint with admin username to set proper password")
        else:
            print("✓ Admin user already exists")
        
        print("\n✓ Database setup completed!")
        cursor.close()
        conn.close()
        
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        raise

if __name__ == "__main__":
    main()
